# Generated by Django 6.0.2 on 2026-05-03 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='procedimento',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('DENTISTA', 'Dentista'), ('PACIENTE', 'Paciente'), ('ADMIN', 'Administrador')], default='PACIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
                ('cro', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('disponibilidade', models.TextField(blank=True, help_text='Ex: Seg a Sex, 08h as 18h', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dentista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='dentista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='api.dentista'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('dentista', 'data_horario')},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='medico',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
