# Generated by Django 6.0.2 on 2026-07-15 03:08

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bloqueios_indisponibilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteCadastroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.gerar_token_convite, editable=False, max_length=64, unique=True)),
                ('telefone_destino', models.CharField(blank=True, max_length=20)),
                ('email_destino', models.EmailField(blank=True, max_length=254)),
                ('nome_destino', models.CharField(blank=True, max_length=255)),
                ('expira_em', models.DateTimeField(default=api.models.expiracao_padrao_convite)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_cadastro_paciente', to='api.clinica')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_cadastro_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['clinica', 'ativo', 'expira_em', 'usado_em'], name='api_convite_clinica_b7b5ca_idx')],
            },
        ),
    ]
