# Generated by Django 6.0.2 on 2026-07-17 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_convitecadastropaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProntuarioPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_atualizados', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='api.clinica')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paciente__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='EvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to='api.agendamento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes_clinicas', to='api.dentista')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='api.prontuariopaciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_em_uso', models.TextField(blank=True)),
                ('condicoes_medicas', models.TextField(blank=True)),
                ('cirurgias_anteriores', models.TextField(blank=True)),
                ('historico_familiar', models.TextField(blank=True)),
                ('gestante', models.BooleanField(blank=True, null=True)),
                ('fumante', models.BooleanField(blank=True, null=True)),
                ('consumo_alcool', models.BooleanField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('preenchida_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('preenchida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses_preenchidas', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anamnese', to='api.prontuariopaciente')),
            ],
        ),
        migrations.AddIndex(
            model_name='prontuariopaciente',
            index=models.Index(fields=['clinica', 'paciente', 'ativo'], name='api_prontua_clinica_6dc80c_idx'),
        ),
        migrations.AddConstraint(
            model_name='prontuariopaciente',
            constraint=models.UniqueConstraint(fields=('clinica', 'paciente'), name='prontuario_unico_por_clinica_paciente'),
        ),
        migrations.AddIndex(
            model_name='evolucaoclinica',
            index=models.Index(fields=['prontuario', 'criado_em'], name='api_evoluca_prontua_6ce559_idx'),
        ),
        migrations.AddIndex(
            model_name='evolucaoclinica',
            index=models.Index(fields=['agendamento', 'dentista'], name='api_evoluca_agendam_9a3c05_idx'),
        ),
    ]
