# Generated by Django 6.0.2 on 2026-07-17 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_prontuariopaciente_evolucaoclinica_anamnese_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas_atualizados', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odontogramas', to='api.clinica')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontogramas_criados', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odontogramas', to='api.prontuariopaciente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PROPOSTO', 'Proposto'), ('APROVADO', 'Aprovado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_tratamento', to='api.clinica')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_tratamento_criados', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_tratamento', to='api.prontuariopaciente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlanoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('numero_dente', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('face', models.CharField(blank=True, choices=[('VESTIBULAR', 'Vestibular'), ('LINGUAL', 'Lingual'), ('PALATINA', 'Palatina'), ('MESIAL', 'Mesial'), ('DISTAL', 'Distal'), ('OCLUSAL', 'Oclusal'), ('INCISAL', 'Incisal'), ('GERAL', 'Geral')], max_length=20, null=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('procedimento_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_plano', to='api.procedimento')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='api.planotratamento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dente', models.PositiveSmallIntegerField()),
                ('face', models.CharField(choices=[('VESTIBULAR', 'Vestibular'), ('LINGUAL', 'Lingual'), ('PALATINA', 'Palatina'), ('MESIAL', 'Mesial'), ('DISTAL', 'Distal'), ('OCLUSAL', 'Oclusal'), ('INCISAL', 'Incisal'), ('GERAL', 'Geral')], max_length=20)),
                ('condicao', models.CharField(choices=[('SAUDAVEL', 'Saudavel'), ('CARIE', 'Carie'), ('RESTAURADO', 'Restaurado'), ('AUSENTE', 'Ausente'), ('FRATURADO', 'Fraturado'), ('IMPLANTE', 'Implante'), ('COROA', 'Coroa'), ('TRATAMENTO_CANAL', 'Tratamento Canal'), ('EXTRACAO_INDICADA', 'Extracao Indicada'), ('PROTESE', 'Protese'), ('OUTRO', 'Outro')], max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_odontograma_criados', to=settings.AUTH_USER_MODEL)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_odontograma', to='api.dentista')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='api.odontograma')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='odontograma',
            constraint=models.UniqueConstraint(fields=('prontuario', 'ativo'), name='odontograma_ativo_unico_por_prontuario'),
        ),
    ]
