# Generated by Django 6.0.2 on 2026-07-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_odontograma_planotratamento_itemplanotratamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemplanotratamento',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AlterModelOptions(
            name='odontograma',
            options={'ordering': ['prontuario__paciente__nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='planotratamento',
            options={'ordering': ['-criado_em']},
        ),
    ]
