# Generated by Django 6.0.2 on 2026-07-18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0013_alter_itemplanotratamento_options_and_more')]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)), ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='RASCUNHO', max_length=20)),
                ('validade_em', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('desconto_tipo', models.CharField(choices=[('NENHUM', 'Nenhum'), ('VALOR', 'Valor'), ('PERCENTUAL', 'Percentual')], default='NENHUM', max_length=12)),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)), ('rejeitado_em', models.DateTimeField(blank=True, null=True)), ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)), ('atualizado_em', models.DateTimeField(auto_now=True)), ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='api.clinica')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to=settings.AUTH_USER_MODEL)),
                ('plano_tratamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='api.planotratamento')),
            ], options={'ordering': ['-criado_em']},
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()), ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)), ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('numero_dente', models.PositiveSmallIntegerField(blank=True, null=True)), ('criado_em', models.DateTimeField(auto_now_add=True)), ('atualizado_em', models.DateTimeField(auto_now=True)), ('ativo', models.BooleanField(default=True)),
                ('item_plano_tratamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='api.itemplanotratamento')),
                ('procedimento_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='api.procedimento')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='api.orcamento')),
            ], options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()), ('valor', models.DecimalField(decimal_places=2, max_digits=12)), ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('paga_em', models.DateTimeField(blank=True, null=True)), ('criado_em', models.DateTimeField(auto_now_add=True)), ('atualizado_em', models.DateTimeField(auto_now=True)), ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='api.clinica')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='api.orcamento')),
            ], options={'ordering': ['numero']},
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartao Credito'), ('CARTAO_DEBITO', 'Cartao Debito'), ('TRANSFERENCIA', 'Transferencia'), ('OUTRO', 'Outro')], max_length=20)),
                ('pago_em', models.DateTimeField(default=django.utils.timezone.now)), ('observacao', models.TextField(blank=True)), ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)), ('criado_em', models.DateTimeField(auto_now_add=True)), ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='api.clinica')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='api.orcamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='api.parcela')),
            ], options={'ordering': ['-pago_em', '-id']},
        ),
        migrations.AddIndex(model_name='orcamento', index=models.Index(fields=['clinica', 'paciente', 'status'], name='api_orcamen_clinica_3eb583_idx')),
        migrations.AddConstraint(model_name='parcela', constraint=models.UniqueConstraint(fields=('orcamento', 'numero'), name='parcela_numero_unico_por_orcamento')),
        migrations.AddConstraint(model_name='pagamento', constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa__isnull', False)), fields=('clinica', 'referencia_externa'), name='pagamento_referencia_unica_por_clinica')),
    ]
