# Generated by Django 6.0.2 on 2026-07-18 02:49

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orcamento_itemorcamento_parcela_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('RADIOGRAFIA', 'Radiografia'), ('EXAME', 'Exame'), ('FOTOGRAFIA', 'Fotografia'), ('DOCUMENTO', 'Documento'), ('RECEITA', 'Receita'), ('ATESTADO', 'Atestado'), ('CONSENTIMENTO', 'Consentimento'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to=api.models.caminho_arquivo_clinico)),
                ('nome_original', models.CharField(editable=False, max_length=255)),
                ('nome_exibicao', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=100)),
                ('tamanho_bytes', models.PositiveBigIntegerField(editable=False)),
                ('descricao', models.TextField(blank=True)),
                ('hash_sha256', models.CharField(editable=False, max_length=64)),
                ('liberado_paciente', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_clinicos', to='api.agendamento')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_clinicos', to='api.clinica')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_clinicos_enviados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_clinicos', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_clinicos', to='api.prontuariopaciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcessoArquivoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VISUALIZACAO', 'Visualizacao'), ('DOWNLOAD', 'Download'), ('DESATIVACAO', 'Desativacao'), ('EXPORTACAO', 'Exportacao')], max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('sucesso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_arquivos_clinicos', to=settings.AUTH_USER_MODEL)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos', to='api.arquivoclinico')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAnonimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EM_ANALISE', 'Em_Analise'), ('PROCESSADA', 'Processada'), ('RECUSADA', 'Recusada')], default='SOLICITADA', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_anonimizacao', to='api.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_anonimizacao', to=settings.AUTH_USER_MODEL)),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonimizacoes_processadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solicitado_em'],
            },
        ),
        migrations.CreateModel(
            name='TermoConsentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('codigo', models.SlugField(max_length=100)),
                ('versao', models.PositiveIntegerField()),
                ('conteudo', models.TextField()),
                ('finalidade', models.TextField(blank=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termos_consentimento', to='api.clinica')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_consentimento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=True)),
                ('aceito_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_pacientes', to='api.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimentos_registrados', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='api.termoconsentimento')),
            ],
            options={
                'ordering': ['-aceito_em'],
            },
        ),
        migrations.AddIndex(
            model_name='arquivoclinico',
            index=models.Index(fields=['clinica', 'paciente', 'ativo'], name='api_arquivo_clinica_2be985_idx'),
        ),
        migrations.AddConstraint(
            model_name='termoconsentimento',
            constraint=models.UniqueConstraint(fields=('codigo', 'versao'), name='termo_codigo_versao_unico'),
        ),
    ]
