# Generated by Django 6.0.2 on 2026-09-25 17:58

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models
from django.db.migrations.operations.models import AddConstraint


class AddPostgresConstraint(AddConstraint):
    """Mantem o estado da constraint no SQLite, mas a cria apenas no PostgreSQL."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_preferenciacomunicacao_options'),
    ]

    operations = [
        BtreeGistExtension(),
        AddPostgresConstraint(
            model_name='agendamento',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['AGENDADA', 'CONFIRMADA', 'EM_ATENDIMENTO', 'CONCLUIDA'])), expressions=[('clinica', '='), ('dentista', '='), (models.Func('data_horario', 'data_hora_fim', function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='agendamento_intervalo_dentista_unico'),
        ),
    ]
